- name: Ping all servers
  hosts: all
  tasks:
  - name: Ping each host
    ping:
      # data: crash 
      data: Ping from Ansible 
    register: ping_answer
  - name: Output ping 
    debug: 
      msg: "Return value of ping is: '{{ping_answer}}'"
